<div id="rev_slider_1_1_wrapper" class="rev_slider_wrapper" style="margin:0px auto;background-color:#E9E9E9;padding:0px;margin-top:0px;margin-bottom:0px;height:350px;width:960px;">
	<div id="rev_slider_1_1" class="rev_slider" style="display:none;height:350px;width:960px;">
<ul>	<!-- SLIDE  -->
	<li data-transition="random" data-slotamount="7" data-masterspeed="300">
		<!-- MAIN IMAGE -->
		<img src="http://192.168.1.184/postheme/pos_auriga_16/modules/revsliderprestashop/images/transparent.png" alt="6117248img-banner1" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
		<!-- LAYERS -->

		<!-- LAYER NR. 1 -->
		<div class="tp-caption big_black tp-fade tp-resizeme" data-x="100" data-y="100" data-speed="300" data-start="500" data-easing="Power3.easeInOut" data-endspeed="300" style="z-index: 2">Caption Text1
		</div>

		<!-- LAYER NR. 2 -->
		<div class="tp-caption large_text tp-fade tp-resizeme" data-x="567" data-y="77" data-speed="300" data-start="800" data-easing="Power3.easeInOut" data-endspeed="300" style="z-index: 3">Caption Text2
		</div>

		<!-- LAYER NR. 3 -->
		<div class="tp-caption lfl ltr" data-x="-5" data-y="217" data-speed="300" data-start="1100" data-easing="Power3.easeInOut" data-end="5000" data-endspeed="300" data-endeasing="Power1.easeIn" style="z-index: 4"><img src="/postheme/pos_auriga_16/modules/revsliderprestashop/uploads/6117248img-banner1.png" alt="">
		</div>
	</li>
</ul>
<div class="tp-bannertimer"></div>	</div>
</div>

<script type="text/javascript">
var tpj=jQuery;				
								
				var revapi1;
				
				jQuery(function($) { alert(1);
								
				if($('#rev_slider_1_1').revolution == undefined)
					revslider_showDoubleJqueryError('#rev_slider_1_1');
				else
				   revapi1 = $('#rev_slider_1_1').show().revolution(
					{
						dottedOverlay:"none",
						delay:9000,
						startwidth:960,
						startheight:350,
						hideThumbs:200,
						
						thumbWidth:100,
						thumbHeight:50,
						thumbAmount:1,
						
						navigationType:"bullet",
						navigationArrows:"solo",
						navigationStyle:"round",
						
						touchenabled:"on",
						onHoverStop:"on",
						
						navigationHAlign:"center",
						navigationVAlign:"bottom",
						navigationHOffset:0,
						navigationVOffset:20,
						soloArrowLeftHalign:"left",
						soloArrowLeftValign:"center",
						soloArrowLeftHOffset:20,
						soloArrowLeftVOffset:0,
						soloArrowRightHalign:"right",
						soloArrowRightValign:"center",
						soloArrowRightHOffset:20,
						soloArrowRightVOffset:0,
								
						shadow:2,
						fullWidth:"off",
						fullScreen:"off",
						stopLoop:"off",
						stopAfterLoops:-1,
						stopAtSlide:-1,
						
						shuffle:"off",
						
												
												
												
												
						hideThumbsOnMobile:"off",
						hideBulletsOnMobile:"off",
						hideArrowsOnMobile:"off",
						hideThumbsUnderResolution:0,
						
						hideSliderAtLimit:0,
						hideCaptionAtLimit:0,
						hideAllCaptionAtLilmit:0,
						startWithSlide:0,
						videoJsPath:"/postheme/pos_auriga_16/modules/revsliderprestashop/rs-plugin/videojs/",
						fullScreenOffsetContainer: ""	
					});
				
				});	//ready
</script>